Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2019-08, with the labels that each got.

#3 Add support of creating avaitrix_firewall, native_egress or native_firewall domain in awsTgw
  aviatrix/resource_aviatrix_aws_tgw.go
  goaviatrix/aws_tgw.go
  goaviatrix/security_domain.go
Labels: size/L

#4 (9850): Fix active_mesh issue for spoke_gateway and transit_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#5 (10308): Fix enable/disable advertise_cidrs issue in vgw_conn due to rest api change
  aviatrix/resource_aviatrix_vgw_conn.go
  goaviatrix/vgw_connection.go
Labels: size/XS

#16 Fix active mesh issue for spoke and transit gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
Labels: size/S

#17 Website link corrections
  website/aviatrix.erb
  website/docs/guides/v2-upgrade-guide.html.markdown
Labels: documentation, size/XS

#18 Website: fix links and markup
  website/aviatrix.erb
  website/docs/d/aviatrix_account.html.markdown
  website/docs/d/aviatrix_caller_identity.html.markdown
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/feature-changelist.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/index.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_account_user.html.markdown
  website/docs/r/aviatrix_arm_peer.html.markdown
  website/docs/r/aviatrix_aws_peer.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_controller_config.html.markdown
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_firewall_tag.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_trans_peer.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
  website/docs/r/aviatrix_vpn_profile.html.markdown
  website/docs/r/aviatrix_vpn_user.html.markdown
  website/docs/r/aviatrix_vpn_user_accelerator.html.markdown
Labels: documentation, size/M

#20 Address failing unit test
  aviatrix/data_source_aviatrix_account_test.go
  aviatrix/data_source_aviatrix_caller_identity_test.go
  aviatrix/data_source_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_account_test.go
  aviatrix/resource_aviatrix_arm_peer_test.go
  aviatrix/resource_aviatrix_aws_peer_test.go
  aviatrix/resource_aviatrix_aws_tgw_test.go
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment_test.go
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn_test.go
  aviatrix/resource_aviatrix_controller_config_test.go
  aviatrix/resource_aviatrix_firewall_test.go
  aviatrix/resource_aviatrix_fqdn_test.go
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_saml_endpoint_test.go
  aviatrix/resource_aviatrix_site2cloud_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_spoke_vpc_test.go
  aviatrix/resource_aviatrix_trans_peer_test.go
  aviatrix/resource_aviatrix_transit_gateway_peering_test.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
  aviatrix/resource_aviatrix_transit_vpc_test.go
  aviatrix/resource_aviatrix_tunnel_test.go
  aviatrix/resource_aviatrix_vgw_conn_test.go
  aviatrix/resource_aviatrix_vpc_test.go
  aviatrix/resource_aviatrix_vpn_profile_test.go
  aviatrix/resource_aviatrix_vpn_user_accelerator_test.go
  aviatrix/resource_aviatrix_vpn_user_test.go
Labels: size/L
