Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2019-11, with the labels that each got.

#155 (11353,11353) Add support of 'Customize Spoke VPC Routes' and 'Disable Local Route Propagation' api parameters in aws_tgw
  aviatrix/resource_aviatrix_aws_tgw.go
  goaviatrix/aws_tgw.go
  goaviatrix/security_domain.go
  website/docs/r/aviatrix_aws_tgw.html.markdown
Labels: documentation, size/L

#157 (11412): Fix acceptance test issue for aviatrix_vpn_user_accelerator
  aviatrix/resource_aviatrix_vpn_user_accelerator.go
Labels: size/XS

#158 Add multiple retries for 'save' or 'synchronize' in data_source_firenet_vendor_integration
  aviatrix/data_source_aviatrix_firenet_vendor_integration.go
Labels: size/S

#159 (11255): Fix import issue for aviatrix_saml_endpoint
  aviatrix/resource_aviatrix_saml_endpoint.go
  website/docs/r/aviatrix_saml_endpoint.html.markdown
Labels: documentation, size/XS

#160 Add two attributes 'number_of_retries' and 'retry_interval in data_source_vendor_integration
  aviatrix/data_source_aviatrix_firenet_vendor_integration.go
  aviatrix/resource_aviatrix_saml_endpoint.go
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
Labels: documentation, size/M

#161 Fix setting 'custom_saml_request_template' in saml_endpoint
  aviatrix/resource_aviatrix_saml_endpoint.go
Labels: size/XS

#162 Change supported versions to 5.0 and 5.1
  aviatrix/provider.go
Labels: size/XS

#163 Change update_access_policy from get to post in firewall
  goaviatrix/firewall.go
Labels: size/XS

#164 Change supported version to 5.1
  aviatrix/provider.go
Labels: size/XS

#165 Release v2.7.0
  CHANGELOG.md
  version
Labels: size/XS

#166 R2.7 documentation updated
  CHANGELOG.md
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
Labels: documentation, size/M

#156 [id=9315] Add support for aws gov access account
  aviatrix/resource_aviatrix_account.go
  aviatrix/resource_aviatrix_account_test.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway_test.go
  goaviatrix/account.go
  test-infra/README_accep_test.md
  test-infra/aviatrix.tf
  test-infra/cmdExportOutput.sh
  test-infra/outputs.tf
  test-infra/provider.tf
  test-infra/variables.tf
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/XL

#169 Update supported version to 5.1 and 5.2
  aviatrix/provider.go
Labels: size/XS

#170 (11522): Add support of 'customized_routes' and 'disable_local_route_propagation' into aws_tgw_vpc_attachment
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw.go
  goaviatrix/aws_tgw_vpc_attachment.go
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
Labels: documentation, size/M

#171 Update markdown of sitecloud and remove two redundent attributes
  aviatrix/resource_aviatrix_site2cloud.go
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/XS

#168 Add missing release dates for R2.6 and R2.7
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#172 Link to view the feature compatibility doc online
  docs/README.md
Labels: size/XS

#173 (11644) Implement new resource aws_tgw_directconnect
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw_directconnect.go
  goaviatrix/aws_tgw_directconnect.go
  website/aviatrix.erb
  website/docs/r/aviatrix_aws_tgw_directconnect.html.markdown
Labels: documentation, size/XL

#174 Update error messages and name of some structs
  aviatrix/resource_aviatrix_aws_tgw_directconnect.go
  goaviatrix/aws_tgw_directconnect.go
Labels: size/M

#175 Remove optional attribute for some arguments
  aviatrix/resource_aviatrix_tunnel.go
  website/docs/r/aviatrix_tunnel.html.markdown
Labels: documentation, size/XS

#176 Implement acceptance test for aws_tgw_directconnect
  aviatrix/resource_aviatrix_aws_tgw_directconnect_test.go
  test-infra/README_accep_test.md
  test-infra/aviatrix.tf
  test-infra/cmdExportOutput.sh
  test-infra/outputs.tf
  test-infra/provider.tf
Labels: size/L

#177 (0011734): Add ability to edit site2cloud resource
  aviatrix/resource_aviatrix_site2cloud.go
Labels: size/M

#179 fix test-infra to include awsgov
  test-infra/aviatrix.tf
  test-infra/outputs.tf
  test-infra/provider.tf
  test-infra/variables.tf
Labels: size/S

#178 Update gateway and s2c docs
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/M

#180 Rewirte create function of aviatrix_gateway to move 'modify spolit tunnel' into 'create gateway'
  aviatrix/resource_aviatrix_gateway.go
Labels: size/L

#181 Block setting back_gateway_name as non-ha_gateway of primary gateway
  aviatrix/resource_aviatrix_site2cloud.go
Labels: size/XS

#182 (11839): Fix the issue where it is unable to manage vpn gw w/split tunnel attributes after creation
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#183 Update test-infra to skip testing for oci, spoke_vpc, and transit_vpc
  test-infra/cmdExportOutput.sh
  test-infra/oci/outputs.tf
  test-infra/outputs.tf
  test-infra/variables.tf
Labels: size/S

#184 Update markdown to replace 'supported values' with 'valid values' to be consistent
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#185 Update test-infra to comment test for awsgov_gateway for 5.2
  test-infra/cmdExportOutput.sh
Labels: size/XS
