Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2019-10, with the labels that each got.

#86 Bypass the issue that enable_vpc_dns_server is incorrectly being set as 'enabled' for arm, gcp and oci
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  test-infra/cmdExportOutput.sh
Labels: size/S

#87 Update changelog for 2.5.0 release
  CHANGELOG.md
  test-infra/cmdExportOutput.sh
  version
Labels: size/XS

#88 Update description format in changelog
  CHANGELOG.md
Labels: size/XS

#89 Update FeatureChangelist, Release Compatibility docs for R2.5
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/feature-changelist.html.markdown
  website/docs/guides/release-compatibility.html.markdown
Labels: documentation, size/XS

#90 (10964): Update all markdowns for attributes and computed values according to AWS
  website/docs/d/aviatrix_account.html.markdown
  website/docs/d/aviatrix_caller_identity.html.markdown
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_arm_peer.html.markdown
  website/docs/r/aviatrix_aws_peer.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_controller_config.html.markdown
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#91 (10863): Add 'single_az_ha' option in resource_aviatrix_transit_gateway
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#92 (10985) Add Release Notes ; Update all documentation links and formatting
  website/aviatrix.erb
  website/docs/guides/changelog.html.markdown
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/feature-changelist.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
Labels: documentation, size/XL

#93 Implement firewall instance with backend fix that firewall instance can be created with disassociated from firenet
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firewall_instance.go
Labels: size/M

#95 Change "oci_api_key_firepath" to "oci_api_key_filepath"
  test-infra/outputs.tf
  test-infra/provider.tf
  test-infra/variables.tf
Labels: size/XS

#94 Update changelog to new formatting to update symlink
  CHANGELOG.md
  website/aviatrix.erb
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XL

#96 Change reference back to new release doc
  CHANGELOG.md
  website/aviatrix.erb
  website/docs/guides/changelog.html.markdown
Labels: documentation, size/XS

#97 Implement fireNet with firewall_instance_association
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firenet.go
  goaviatrix/firewall_instance.go
Labels: documentation, size/XL

#98 Implement option to associate FQDN gateway to firenet
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firenet.go
  goaviatrix/firewall_instance.go
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall_instance.html.markdown
Labels: documentation, size/L

#99 (11055&11054) Fix the issue that updating account_number causes crash
  aviatrix/resource_aviatrix_account.go
Labels: size/XS

#100 (10434): Separate subnets to public and private subnets
  aviatrix/resource_aviatrix_vpc.go
  goaviatrix/vpc.go
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#101 Implement associating/disassociating fqdn-gw to/from fireNet
  aviatrix/resource_aviatrix_firenet.go
  goaviatrix/firenet.go
Labels: documentation, size/M

#102 Make active_mesh be enabled in creation of spoke_gateway and transit_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#103 (11118) Fix the issue that updating connected_domains causes terraform crash
  aviatrix/resource_aviatrix_aws_tgw.go
Labels: size/XS

#104 (11113) Update doc with versioning references to provider
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/M

#106 (11123) Update docs to reflect vgw_conn and transit_gateway changes
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
Labels: documentation, size/XS

#107 Implement acceptance test for aviatrix_firewall_instance and aviatrix_firenet
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_firenet_test.go
  aviatrix/resource_aviatrix_firewall_instance.go
  aviatrix/resource_aviatrix_firewall_instance_test.go
  goaviatrix/firenet.go
  goaviatrix/firewall_instance.go
  test-infra/README_accep_test.md
Labels: size/XL

#108 Update description of "connected_transit" in transit_gateway
  website/docs/r/aviatrix_controller_config.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#109 Update markdown of firenet to add more description of arguments
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall_instance.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vpn_profile.html.markdown
  website/docs/r/aviatrix_vpn_user_accelerator.html.markdown
Labels: documentation, size/XS

#110 (0011087): Add option to use byol for terraform acceptance (test-infra)
  test-infra/aviatrix.tf
  test-infra/variables.tf
Labels: size/XS

#111 Add skip parameters for firenet and firewall_instance in test-infra
  test-infra/cmdExportOutput.sh
Labels: size/XS

#112 Update "gw_name" to "firenet_gw_name" in aviatrix_firewall_instance and aviatrix_firenet
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_firenet_test.go
  aviatrix/resource_aviatrix_firewall_instance.go
  aviatrix/resource_aviatrix_firewall_instance_test.go
  goaviatrix/firenet.go
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall_instance.html.markdown
Labels: documentation, size/S

#113 Add support to create firewall_instance with iam_role and bootstrap_bucket_name
  goaviatrix/firewall_instance.go
Labels: size/XS

#114 (11210): Update avaitrix_firenet to catch invalid vendor_type
  aviatrix/resource_aviatrix_firenet.go
Labels: size/XS

#116 (11223) Fix the issue that firenet resource incorrectly creates inspection and egress setting as false if set to true
  aviatrix/resource_aviatrix_firenet.go
  website/docs/r/aviatrix_firenet.html.markdown
Labels: documentation, size/XS

#115 Implement data_source_aviatrix_firenet_vendor_integration for vendor integration
  aviatrix/data_source_aviatrix_firenet_vendor_integration.go
  aviatrix/data_source_aviatrix_firenet_vendor_integration_test.go
  aviatrix/provider.go
  goaviatrix/vendor_integration.go
  website/docs/d/aviatrix_account.html.markdown
  website/docs/d/aviatrix_caller_identity.html.markdown
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
  website/docs/d/aviatrix_gateway.html.markdown
Labels: documentation, size/XL

#117 Add default value false for save and synchronize in vendor integration data source
  aviatrix/data_source_aviatrix_firenet_vendor_integration.go
Labels: size/XS

#118 Update supported_version to 5.2
  aviatrix/provider.go
Labels: size/XS

#119 Update test-infra to add test for firenet_vendor_integration
  test-infra/README_accep_test.md
  test-infra/cmdExportOutput.sh
Labels: size/XS

#121 Add printing err body when could not decode output of rest api to terraform for all rest apis
  goaviatrix/account.go
  goaviatrix/account_user.go
  goaviatrix/arm_peering.go
  goaviatrix/aws_peering.go
  goaviatrix/aws_tgw.go
  goaviatrix/aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw_vpn_conn.go
  goaviatrix/controller.go
  goaviatrix/firenet.go
  goaviatrix/firewall.go
  goaviatrix/firewall_instance.go
  goaviatrix/firewall_tag.go
  goaviatrix/fqdn.go
  goaviatrix/gateway.go
  goaviatrix/profile.go
  goaviatrix/saml_endpoint.go
  goaviatrix/security_domain.go
  goaviatrix/site2cloud.go
  goaviatrix/split_tunnel.go
  goaviatrix/spoke_vpc.go
  goaviatrix/tags.go
  goaviatrix/transit_gateway_peering.go
  goaviatrix/transit_vpc.go
  goaviatrix/transitive_peering.go
  goaviatrix/tunnel.go
  goaviatrix/vendor_integration.go
  goaviatrix/version.go
  goaviatrix/vgw_connection.go
  goaviatrix/vpc.go
  goaviatrix/vpn_user.go
  goaviatrix/vpn_user_accelerator.go
Labels: size/XXL

#122 Update markdown of firewall_instance and firenet
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall_instance.html.markdown
Labels: documentation, size/XS

#123 Update test-infra to export skip_firenet and skip_firewall_instance
  test-infra/cmdExportOutput.sh
Labels: size/XS

#124 Fix an potential nil point dereference issue
  aviatrix/resource_aviatrix_aws_tgw.go
Labels: size/XS

#125 Update erb to add resource firenet, firewall_instance and data source firenet_vendor_integration
  website/aviatrix.erb
Labels: documentation, size/XS

#126 Release 2.6.0
  CHANGELOG.md
  version
Labels: size/XS

#128 Add description of enable/disable single_az_ha in aviatrix_transit_gateway as an enhancement
  CHANGELOG.md
Labels: size/XS

#127 R2.6: Update Compatibility chart, Release Notes and Changelist
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/S

#129 Put description of terraform import when manage_vpc_attachment is set false into a note
  website/docs/r/aviatrix_aws_tgw.html.markdown
Labels: documentation, size/XS

#130 Change supportedVersion to a list of supported controller versions
  aviatrix/provider.go
  goaviatrix/check.go
Labels: size/S

#131 (11157): add support of Force Drop policy in stateful firewall
  aviatrix/resource_aviatrix_firewall.go
  goaviatrix/firewall.go
  goaviatrix/utils.go
  website/docs/r/aviatrix_firewall.html.markdown
Labels: documentation, size/M

#132 (11276): Fix the issue where it is unable to disable gateway 'split_tunnel'
  aviatrix/resource_aviatrix_gateway.go
Labels: size/S

#133 Update description of some attributes in firenet markdown
  aviatrix/resource_aviatrix_firenet.go
  website/docs/r/aviatrix_firenet.html.markdown
Labels: documentation, size/XS

#134 Fix the issue where terraform refresh is not working for firewall policy
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_firewall.go
Labels: size/XS

#135 Change supportedVersion to 5.1 only for master branch
  aviatrix/provider.go
Labels: size/XS

#137 Fix version validation issue
  goaviatrix/check.go
Labels: size/XS

#138 Fix terraform import issue for firewall regarding policy
  aviatrix/resource_aviatrix_firewall.go
Labels: size/S

#139 (11274): Add support of creating aviatrix_vpc for GCP provider
  aviatrix/resource_aviatrix_vpc.go
  goaviatrix/vpc.go
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/L

#140 Update the logic for updating single_az_ha for gateway
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#141 (11255): Add support of custom saml request template in saml_endpoint
  aviatrix/resource_aviatrix_saml_endpoint.go
  goaviatrix/saml_endpoint.go
  website/docs/r/aviatrix_saml_endpoint.html.markdown
Labels: documentation, size/L

#142 (113120): Fix subnets reorder issue after import
  aviatrix/resource_aviatrix_vpc.go
Labels: size/XS

#144 Add support of enable/disable vpn_nat for vpn gateway in aviatrix_gateway
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/M

#146 (11326):Fix the issue that 'public_subnets' is not being set after initial creation for firenet vpc
  aviatrix/resource_aviatrix_vpc.go
Labels: size/XS

#147 (11329): Fix the issue where creating with '_' character causes parsing issue
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firewall_instance.go
Labels: size/XS

#148 (11329): Fix the issue where creating with '_' character causes parsing issue
  goaviatrix/firewall_instance.go
Labels: size/XS

#149 Revert separating subnets to public_subnets and private_subnets in aviatrix_vpc
  aviatrix/resource_aviatrix_vpc.go
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#150 Update markdown of aws_tgw_vpc_attachment
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
Labels: documentation, size/XS

#152 Update supportedVersions to 5.0~5.2
  aviatrix/provider.go
Labels: size/XS

#153 (11330): Add support of attaching/detaching FireNet gateway to/from TGW Firewall Domain
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw.go
  goaviatrix/aws_tgw_vpc_attachment.go
  goaviatrix/vpc.go
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_controller_config.html.markdown
Labels: documentation, size/L

#154 (11369): Fix acceptance test for aws_tgw_vpc_attachment
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw.go
  goaviatrix/vpc.go
Labels: size/M
