Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2019-09, with the labels that each got.

#22 (10180): Add transit gateway support for GCP provider
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
Labels: size/XS

#23 Update transit gateway markdown to add GCP support description
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#25 Create new firewall_instance resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firewall_instance.go
Labels: size/XL

#28 Implement FireNet resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_firenet.go
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/firenet.go
  goaviatrix/firewall_instance.go
Labels: size/XL

#30 Update markdown of aviatrix provider
  website/docs/index.html.markdown
Labels: documentation, size/XS

#32 Update doc links to new github
  README.md
  docs/README.md
  examples/fullmesh.tf
  goaviatrix/README_goaviatrix.md
  website/docs/guides/v2-upgrade-guide.html.markdown
Labels: documentation, size/XS

#40 Release v2.3.35
  CHANGELOG.md
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_vgw_conn.go
  aviatrix/resource_aviatrix_vgw_conn_test.go
  aviatrix/resource_aviatrix_vpc.go
  docs/FeatureCompatibility.xlsx
  docs/README.md
  goaviatrix/aws_tgw.go
  goaviatrix/gateway.go
  goaviatrix/security_domain.go
  goaviatrix/spoke_vpc.go
  goaviatrix/transit_vpc.go
  goaviatrix/vgw_connection.go
  goaviatrix/vpc.go
  version
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/index.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
Labels: documentation, size/XL

#43 Fix acceptance tests
  aviatrix/resource_aviatrix_arm_peer_test.go
  aviatrix/resource_aviatrix_aws_peer_test.go
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_saml_endpoint_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_spoke_vpc.go
  aviatrix/resource_aviatrix_spoke_vpc_test.go
  aviatrix/resource_aviatrix_trans_peer_test.go
  aviatrix/resource_aviatrix_transit_gateway_peering_test.go
  aviatrix/resource_aviatrix_tunnel_test.go
  aviatrix/resource_aviatrix_vgw_conn_test.go
  aviatrix/resource_aviatrix_vpn_user_accelerator.go
  aviatrix/resource_aviatrix_vpn_user_accelerator_test.go
  test-infra/outputs.tf
Labels: size/L

#44 Release v2.3.36
  CHANGELOG.md
  version
Labels: size/XS

#45 Change release format in changelog
  CHANGELOG.md
Labels: size/XS

#47 Add support of Oracle cloud in gateway resources
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#48 (10645): Fix the issue that GCP transit GW fails to create HA GW
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#49 (10689): Update the gateway HA examples in docs
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/S

#50 (10685): Add a check for peering_ha_zone being set for enabling HA for gateway not of GCP provider
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#52 Update preview version
  aviatrix/provider.go
Labels: size/XS

#53 (10746): Fix the issue that ha gw could not be deleted before primary gw for GCP
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#56 Add Release Compatibility Chart
  website/aviatrix.erb
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/feature-changelist.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
Labels: documentation, size/M

#51 (10735): Update error message when terraform version does not match controller version
  goaviatrix/check.go
Labels: size/XS

#57 Update format of 'NOTE' section in markdown of all related resources
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/S

#58 (10827): Add "description" as an attribute under policy in firewall resource
  aviatrix/resource_aviatrix_firewall.go
  goaviatrix/firewall.go
  website/docs/r/aviatrix_firewall.html.markdown
Labels: documentation, size/S

#59 (10832): Fix the issue which is unable to create oci vpn-gw with no elb-name specified
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#60 (10757): Increase sleep time from 3min to 4min for vpn user to be active in vpn_user_accelerator
  aviatrix/resource_aviatrix_vpn_user_accelerator.go
Labels: size/XS

#61 Implement acceptance test for oci gw, spoke_gw and transit_gw
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
Labels: size/L

#62 Add OCI support in resource_aviatrix_account
  aviatrix/resource_aviatrix_account.go
  goaviatrix/account.go
  goaviatrix/utils.go
Labels: size/M

#65 Implement acceptane test for oci provider in account
  aviatrix/resource_aviatrix_account.go
  aviatrix/resource_aviatrix_account_test.go
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
  test-infra/README_accep_test.md
Labels: size/XL

#67 Rename go-aviatrix Readme
  goaviatrix/README.md
Labels: size/XS

#66 Update test-infra to add infra needed for oci acceptance test
  test-infra/aviatrix.tf
  test-infra/oci/main.tf
  test-infra/oci/outputs.tf
  test-infra/oci/vars.tf
  test-infra/outputs.tf
  test-infra/provider.tf
  test-infra/variables.tf
Labels: size/M

#68 Fix the issue that attached vpn is read as attache_vpc in resource aws_tgw
  goaviatrix/aws_tgw.go
Labels: size/XS

#69 (10832): Fix modify split_tunnel issue when no elb-name specified
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#70 (10878): Fix the issue that Terraform Import does not import OCI transit_gateway ha_subnet
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#71 Update markdown of account to add support for OCI provider
  website/docs/r/aviatrix_account.html.markdown
Labels: documentation, size/XS

#72 Update descriptions in markdown of gw, transit_gw and spoke_gw
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#73 (10879): Fix the issue that terraform is unable to enable HA for OCI spoke_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/spoke_vpc.go
Labels: size/XS

#74 Fix credential file upload issue in account
  aviatrix/resource_aviatrix_account.go
  goaviatrix/account.go
Labels: size/XS

#75 Update changelog for 2.4.0 release
  CHANGELOG.md
  aviatrix/resource_aviatrix_vpc.go
  version
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/S

#76 Update Release Compatibility, FeatureChangelistv2 for R2.4
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/index.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/S

#77 Update markdown of vpc resource to add more description of attribute
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#78 Update computed attributes in vpc markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#80 Update markdown of vpc to add description of firenet vpc
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#81 (10873) Add enable/disable vpc_dns_server for gw, transit_gw and spoke_gw
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  goaviatrix/spoke_vpc.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
Labels: documentation, size/L

#82 Implement a shell tool to export test-infra output for acceptance test
  test-infra/cmdExportOutput.sh
Labels: size/L

#83 Update description of enable_vpc_dns_server in all docs
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
Labels: documentation, size/XS

#84 Update description of subnets created along with firenet vpc creation in vpc markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#85 Add an oci internet gw in oci module in test-infra
  test-infra/oci/main.tf
Labels: size/XS
