Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2019-12, with the labels that each got.

#186 Update test-infra to use name of gcp-vpc as "gcp_vpc_id"
  test-infra/gcp/outputs.tf
Labels: size/XS

#187 (11978): Fix the issue where controller does not take port of '0:65535' for protocol of 'all' type
  aviatrix/resource_aviatrix_firewall.go
  goaviatrix/firewall.go
Labels: size/XS

#188 Format change to be consistent for all resources
  aviatrix/data_source_aviatrix_account_test.go
  aviatrix/data_source_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_account_test.go
  aviatrix/resource_aviatrix_arm_peer_test.go
  aviatrix/resource_aviatrix_aws_peer_test.go
  aviatrix/resource_aviatrix_aws_tgw_test.go
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment_test.go
  aviatrix/resource_aviatrix_controller_config_test.go
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_site2cloud_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_transit_gateway_peering_test.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
  aviatrix/resource_aviatrix_vpc_test.go
Labels: size/S

#189 Release v2.8.0
  CHANGELOG.md
  version
Labels: size/XS

#191 Add support to allow back_gateway_name to be another primary gateway
  aviatrix/resource_aviatrix_site2cloud.go
  goaviatrix/site2cloud.go
Labels: size/XS

#192 Update changelog to remove the 'enhancement' in site2cloud
  CHANGELOG.md
Labels: size/XS

#193 Remove redundent period to be consistent for all resource markdowns
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
  website/docs/r/aviatrix_vpn_profile.html.markdown
Labels: documentation, size/XS

#190 R2.8 Release Notes + doc updates
  docs/FeatureCompatibility.xlsx
  docs/README.md
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/feature-changelist.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_account_user.html.markdown
  website/docs/r/aviatrix_arm_peer.html.markdown
  website/docs/r/aviatrix_aws_peer.html.markdown
  website/docs/r/aviatrix_aws_tgw_directconnect.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_controller_config.html.markdown
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_firewall_tag.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_trans_peer.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
  website/docs/r/aviatrix_vpn_profile.html.markdown
  website/docs/r/aviatrix_vpn_user.html.markdown
  website/docs/r/aviatrix_vpn_user_accelerator.html.markdown
Labels: documentation, size/L

#194 Update markdown of aws_tgw_vpn_conn
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
Labels: documentation, size/XS

#196 Update supported version of controller to 5.2.1987
  CHANGELOG.md
Labels: size/XS

#195 (11612) Block creation of 'transit_vpc' and 'firenet_vpc' for non-AWS cloudtype in aviatrix_vpc
  aviatrix/resource_aviatrix_vpc.go
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#197 Update supported version in release notes
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#198 Implement enable/disable 'designated_gateway' feature in aviatrix_gateway
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/XL

#199 Remove cloud_type check for setting desiganted_gateway in aviatrix_gateway
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
Labels: size/XS

#200 (12073) Add support for enabling Encrypt EBS volume for gateway
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#202 Implement new resource aviatrix_geo_vpn
  aviatrix/provider.go
  aviatrix/resource_aviatrix_geo_vpn.go
  goaviatrix/geo_vpn.go
  website/aviatrix.erb
  website/docs/r/aviatrix_geo_vpn.html.markdown
Labels: documentation, size/XL

#204 Implement custom SNAT feature for spoke_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XL

#206 Add 'elb_dns_name' as a computed attribute in aviatrix_gateway
  aviatrix/resource_aviatrix_gateway.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XS

#207 Implement DSAT for aviatrix_gateway and aviatrix_spoke_gateway
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XL

#209 Implement acceptance test for aviatrix_geo_vpn
  aviatrix/resource_aviatrix_geo_vpn_test.go
  goaviatrix/geo_vpn.go
  test-infra/README_accep_test.md
  website/docs/r/aviatrix_geo_vpn.html.markdown
Labels: documentation, size/L

#210 Update test-infra to add coverage for aviatrix_geo_vpn
  aviatrix/resource_aviatrix_geo_vpn_test.go
  test-infra/aws/main.tf
  test-infra/cmdExportOutput.sh
  test-infra/gcp/main.tf
  test-infra/outputs.tf
  test-infra/provider.tf
  test-infra/variables.tf
Labels: size/S

#211 Update supported controller versions to 5.2 only
  aviatrix/provider.go
Labels: size/XS

#212 (12221): Add a check to error out that 'enable_sant' is set false and 'snat_mode' is not empty or 'primary'
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/XS

#213 Update descriptions and error messages for SNAT feature in aviatrix_spoke_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/XS

#214 (12226): Solve the issue where gateway's additional_cidrs_designated_gateway reads a diff when refreshing after create
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#215 (12243) Fix the issue where transit_gateway enable_snat fails
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
Labels: size/S

#216 Release v2.9.0
  CHANGELOG.md
  version
Labels: size/XS

#217 R2.9 Documentation update
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/M

#218 Update site side-bar for intuitive navigation
  website/aviatrix.erb
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XL

#219 Update supporte version to UserConnect-5.2.2048
  CHANGELOG.md
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS
