Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-08, with the labels that each got.

#503 Release v2.16.0
  CHANGELOG.md
  version
Labels: size/XS

#509 Doc updates for R2.16
  docs/FeatureCompatibility.xlsx
  website/aviatrix.erb
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_periodic_ping.html.markdown
Labels: documentation, size/S

#486 (15350) Add fqdn_tag_rule resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_fqdn.go
  aviatrix/resource_aviatrix_fqdn_tag_rule.go
  aviatrix/resource_aviatrix_fqdn_tag_rule_test.go
  goaviatrix/fqdn.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_fqdn_tag_rule.html.markdown
Labels: documentation, size/XL

#488 (15350) Add firewall_policy resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_firewall.go
  aviatrix/resource_aviatrix_firewall_policy.go
  aviatrix/resource_aviatrix_firewall_policy_test.go
  goaviatrix/firewall.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_firewall_policy.html.markdown
Labels: documentation, size/XL

#533 Update supported Controller version for R2.16.2
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation
