Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-07, with the labels that each got.

#466 (13388) Remove 'commit' option from branch_router_tag resource
  aviatrix/resource_aviatrix_branch_router_tag.go
  aviatrix/resource_aviatrix_branch_router_tag_test.go
  goaviatrix/branch_router_tag.go
  website/docs/r/aviatrix_branch_router_tag.html.markdown
Labels: documentation, size/M

#468 (13388) branch router aws tgw attachment
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router_avx_tgw_attachment.go
  aviatrix/resource_aviatrix_branch_router_aws_tgw_attachment.go
  aviatrix/resource_aviatrix_branch_router_aws_tgw_attachment_test.go
  goaviatrix/aws_tgw_transit_gateway_attachment.go
  goaviatrix/branch_router.go
  goaviatrix/branch_router_avx_tgw_attachment.go
  goaviatrix/branch_router_aws_tgw_attachment.go
  test-infra/README_accep_test.md
  website/docs/r/aviatrix_branch_router_aws_tgw_attachment.html.markdown
Labels: documentation, size/XL

#470 (13112) Periodic ping resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_periodic_ping.go
  aviatrix/resource_aviatrix_periodic_ping_test.go
  goaviatrix/periodic_ping.go
  test-infra/README_accep_test.md
  website/docs/r/aviatrix_periodic_ping.html.markdown
Labels: documentation, size/XL

#471 (13388) Branch router azure vwan attachment
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router_virtual_wan_attachment.go
  aviatrix/resource_aviatrix_branch_router_virtual_wan_attachment_test.go
  goaviatrix/branch_router_virtual_wan_attachment.go
  goaviatrix/site2cloud.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_branch_router_aws_tgw_attachment.html.markdown
  website/docs/r/aviatrix_branch_router_virtual_wan_attachment.html.markdown
Labels: documentation, size/XL

#474 Release v2.15.1
  CHANGELOG.md
  version
Labels: size/XS

#475 Doc update for 2.15.1 minor release
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#476 Fix an overflow issue from HashiCorp side
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_vgw_conn.go
Labels: size/XS

#477 Update validation function for ASN
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_vgw_conn.go
Labels: size/S

#478 (13388) Separate interface configuration from branch router resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router.go
  aviatrix/resource_aviatrix_branch_router_interface_config.go
  aviatrix/resource_aviatrix_branch_router_interface_config_test.go
  aviatrix/resource_aviatrix_branch_router_test.go
  goaviatrix/branch_router.go
  test-infra/README_accep_test.md
  website/docs/r/aviatrix_branch_router.html.markdown
  website/docs/r/aviatrix_branch_router_avx_tgw_attachment.html.markdown
  website/docs/r/aviatrix_branch_router_aws_tgw_attachment.html.markdown
  website/docs/r/aviatrix_branch_router_interface_config.html.markdown
  website/docs/r/aviatrix_branch_router_virtual_wan_attachment.html.markdown
Labels: documentation, size/XL

#479 (13388) Rename cloudwan resources
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router_interface_config_test.go
  aviatrix/resource_aviatrix_branch_router_registration.go
  aviatrix/resource_aviatrix_branch_router_registration_test.go
  aviatrix/resource_aviatrix_branch_router_transit_gateway_attachment.go
  aviatrix/resource_aviatrix_branch_router_transit_gateway_attachment_test.go
  goaviatrix/branch_router_transit_gateway_attachment.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_branch_router_registration.html.markdown
  website/docs/r/aviatrix_branch_router_transit_gateway_attachment.html.markdown
Labels: documentation, size/XL

#480 (13388) Remove branch router HA on transit gateway attachment
  aviatrix/resource_aviatrix_branch_router_transit_gateway_attachment.go
  goaviatrix/branch_router_transit_gateway_attachment.go
  website/docs/r/aviatrix_branch_router_transit_gateway_attachment.html.markdown
Labels: documentation, size/S

#481 (15672) Add 4 new transit gateway advanced config options
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_vgw_conn.go
  goaviatrix/client.go
  goaviatrix/transit_vpc.go
  goaviatrix/utils.go
  goaviatrix/utils_test.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XL

#482 Setup basic github action for building and testing
  .github/workflows/go.yml
  .golangci.toml
Labels: size/M

#483 Fix documentation formatting
  .github/workflows/go.yml
  goaviatrix/branch_router.go
  website/docs/d/aviatrix_vpc_tracker.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
Labels: documentation, size/XS

#484 (15994) support enable_vpc_dns_server for controller
  aviatrix/resource_aviatrix_controller_config.go
  aviatrix/resource_aviatrix_controller_config_test.go
  goaviatrix/client.go
  goaviatrix/controller.go
  website/docs/r/aviatrix_controller_config.html.markdown
Labels: documentation, size/M

#487 update supported version to 6.1
  aviatrix/provider.go
Labels: size/XS

#485 Enable more linters, but only for last commit
  .github/workflows/go.yml
  .golangci.toml
Labels: size/XS

#490 16302: Allow changing name servers individually on GeoVPN
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#489 (15989) Allow allocate_new_eip to be false on GCP
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/S

#491 (15825) Sync to HA option on gateway_snat and gateway_dnat
  aviatrix/resource_aviatrix_gateway_dnat.go
  aviatrix/resource_aviatrix_gateway_snat.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway_dnat.html.markdown
  website/docs/r/aviatrix_gateway_snat.html.markdown
Labels: documentation, size/S

#493 0016205: Fix TGW Peering being read in the deltas of the TGW due to a backend exception
  goaviatrix/aws_tgw.go
Labels: size/XS

#495 (15989) Fix allocate_new_eip for GCP gateway data sources
  aviatrix/data_source_aviatrix_gateway.go
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway.go
Labels: size/XS

#494 (15825) Change DNAT sync_to_ha to default true
  aviatrix/resource_aviatrix_gateway_dnat.go
  website/docs/r/aviatrix_gateway_dnat.html.markdown
Labels: documentation, size/XS

#496 Fix value set issue for 'local_as_number' in aviatrix_transit_gateway
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#498 Update 'local_as_number' set condition to fix acceptance test failure
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#497 (16520) Update test-infra
  test-infra/cmdExportOutput.sh
Labels: size/XS

#500 (16533) Pass sync_to_ha to delete functions
  aviatrix/resource_aviatrix_gateway_dnat.go
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/XS

#501 16302:Allow changing addional cidr servers individually on GeoVPN to …
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#502 (15989) Fix GCP hagw eip
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#504 (16544) Use TypeSet instead of TypeList for snat policies
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/XS

#505 (16583) Only update transit gateway ha gw size if necessary
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#506 (16585) Prevent updating eip attributes on transit and spoke gw
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#508 (16544) Use TypeList and dedup the policies before writing to state
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/XS
