Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-01, with the labels that each got.

#223 (0012387): Fix the issue where exporting TGW and importing leave deltas not rectified thru apply
  aviatrix/resource_aviatrix_aws_tgw.go
Labels: size/XS

#222 (12142) Added grouping for gateway, spoke and transit attributes in docs
  website/docs/index.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#221 Added missing import section for GeoVPN doc
  website/docs/r/aviatrix_geo_vpn.html.markdown
Labels: documentation, size/XS

#224 Update FireNet doc to include info on dependencies and proper config
  website/docs/r/aviatrix_firenet.html.markdown
Labels: documentation, size/XS

#225 Update index.html to include environment var auth option for Aviatrix…
  website/docs/index.html.markdown
Labels: documentation, size/S

#226 (12409) Implement data source for transit gateway
  aviatrix/data_source_aviatrix_transit_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway_test.go
  aviatrix/provider.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
  website/docs/d/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XL

#227 (12409) Implement data source for spoke gateway
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_spoke_gateway_test.go
  aviatrix/provider.go
  website/docs/d/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XL

#228 Update test-infra to add test parameters for data sources of spoke gateway and transit gateway
  test-infra/cmdExportOutput.sh
Labels: size/XS

#229 (12249) Implement advanced VPC attachment feature in TGW Orchestrator
  aviatrix/resource_aviatrix_aws_tgw.go
  goaviatrix/aws_tgw.go
  goaviatrix/security_domain.go
  website/docs/r/aviatrix_aws_tgw.html.markdown
Labels: documentation, size/L

#230 (12249) Implement advanced VPC attachment feature in aws_tgw_vpc_attachment resource
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw_vpc_attachment.go
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
Labels: documentation, size/M

#233 (0012488) Implement data source for aviatrix_firenet
  aviatrix/data_source_aviatrix_firenet.go
  aviatrix/data_source_aviatrix_firenet_test.go
  aviatrix/provider.go
  website/docs/d/aviatrix_firenet.html.markdown
Labels: documentation, size/XL

#234 (12521) Implement updating customized_routes in aws_tgw_vpc_attachment resource
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw_vpc_attachment.go
Labels: size/S

#232 (12485) Added notes for FireNet Panorama integration
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
Labels: documentation, size/XS

#235 Update test-infra to add test for data_source_aviatrix_firenet
  test-infra/cmdExportOutput.sh
Labels: size/XS

#237 (0012494) Add a check that aws_account_number should be 12 digits
  aviatrix/resource_aviatrix_account.go
  website/docs/r/aviatrix_account.html.markdown
Labels: documentation, size/XS

#238 (12494) Use ValidateFunc to check if aws_account_number is 12 digits
  aviatrix/resource_aviatrix_account.go
Labels: size/XS

#236 (12248) Implement multiple missing parameters for spoke gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XL

#239 (12248) Implement multiple missing parameters for transit gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#240 0012557: Fix the issue where aws_tgw resource can not detach VPC from security domain
  aviatrix/resource_aviatrix_aws_tgw.go
Labels: size/XS

#242 Update data source transit gateway to add more parameters to export
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway.go
  website/docs/d/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#243 Differenciate spoke gateway and transit gateway for 'Filter Advertised Spoke VPC CIDRS'
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/d/aviatrix_spoke_gateway.html.markdown
  website/docs/d/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#244 (12353) Implement SNAT through a sepatate resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_source_nat.go
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/XL

#245 (12353) Implement support of DNAT for gateway through a separate resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_destination_nat.go
  aviatrix/resource_aviatrix_source_nat.go
Labels: size/L

#246 (12248) Update names and descriptions of the attributes added for spoke gateway and transit gateway
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  website/docs/d/aviatrix_spoke_gateway.html.markdown
  website/docs/d/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XL

#248 (12248) Update names of two attributes
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/d/aviatrix_spoke_gateway.html.markdown
  website/docs/d/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#247 (0012648) Fix the issue where Json Decode get_site2cloud_conn_detail failed
  goaviatrix/site2cloud.go
  goaviatrix/vgw_connection.go
Labels: size/S

#249 (12353) Update name of the two new resources added
  aviatrix/provider.go
  aviatrix/resource_aviatrix_gateway_dnat.go
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/S

#250 (12353) Update allowd types for 'snat_mode'
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/S

#251 (0012353) Implement configuring policies for NAT function mode of 'customized_snat' for gateway in a new resource
  aviatrix/resource_aviatrix_gateway_snat.go
  website/docs/r/aviatrix_gateway_snat.html.markdown
Labels: documentation, size/L

#253 Deprecate dnat_policy and replace "enable_snat" with "single_ip_snat" in gateway resource
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway_dnat.go
  aviatrix/resource_aviatrix_gateway_snat.go
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/L

#254 Deprecate dnat and snat features in spoke gateway resource
  aviatrix/resource_aviatrix_spoke_gateway.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XL

#255 Update 'enable_snat' to 'single_ip_snat' in transit gateway resource
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#257 Fix set issue for 'included_advertised_spoke_routes' in spoke gateway resource
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/gateway.go
Labels: size/XS

#258 (0012648) Fix the issue where Json Decode get_site2cloud_conn_detail failed (#247)
  goaviatrix/site2cloud.go
  goaviatrix/vgw_connection.go
Labels: size/S

#260 Release v2.9.1
  CHANGELOG.md
  version
Labels: size/XS

#262 Implement acceptance test for "aviatrix_gateway_dnat"
  aviatrix/resource_aviatrix_gateway_dnat_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
Labels: documentation, size/L

#259 Implement acceptance test for new resource "aviatrix_gateway_snat"
  aviatrix/resource_aviatrix_gateway_snat_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
Labels: documentation, size/XL

#263 Update test-infra to add tests for 'gateway_dnat' and 'gateway_snat'
  test-infra/cmdExportOutput.sh
Labels: size/XS

#264 Update acceptance tests for "gateway_dnat" and "gateway_snat"
  aviatrix/resource_aviatrix_gateway_dnat_test.go
  aviatrix/resource_aviatrix_gateway_snat_test.go
  test-infra/cmdExportOutput.sh
Labels: size/M

#266 (12732) Fix issue where aws_tgw import and them apply fails
  aviatrix/resource_aviatrix_aws_tgw.go
  goaviatrix/utils.go
Labels: size/S

#268 Fix acceptance test failing for 'enable_snat' being updated to 'single_ip_snat'
  aviatrix/data_source_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_fqdn_test.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
Labels: size/M

#267 (0012715) Fix the issue where spoke gateway does not handle 'included_advertised_spoke_routes' when HA is created
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/XS

#265 Update documentation for R2.10 (WIP)
  website/aviatrix.erb
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_gateway_dnat.html.markdown
  website/docs/r/aviatrix_gateway_snat.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#269 (12730) Fix issue where spoke and transit gateway 'filtered_spoke_vpc_routes' return output is descending and causes diff
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/L

#271 (12548) Implement functionality of enabling/disabling cloudn backup config for controller
  aviatrix/resource_aviatrix_controller_config.go
  goaviatrix/controller.go
  website/docs/r/aviatrix_controller_config.html.markdown
Labels: documentation, size/L

#270 Update deprecation notes for SNAT/DNAT
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#272 (12548) Update delete func for backup_configuration in controller_config resource
  aviatrix/resource_aviatrix_controller_config.go
Labels: size/XS
