Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-02, with the labels that each got.

#275 (0012548) Fix acceptance test issue for adding cloudn config backup
  aviatrix/resource_aviatrix_controller_config.go
  aviatrix/resource_aviatrix_controller_config_test.go
Labels: size/S

#276 (0012548) Update descriptions
  aviatrix/resource_aviatrix_controller_config.go
Labels: size/XS

#277 (0012548) Update logic in update func
  aviatrix/resource_aviatrix_controller_config.go
Labels: size/M

#278 Release v2.10.0
  CHANGELOG.md
  version
Labels: size/S

#279 Update documentation for R2.10
  docs/FeatureCompatibility.xlsx
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_vpn_user.html.markdown
Labels: documentation, size/S

#280 (0012871) Implement support of elb protocol for vpn gateway of aws provider with elb enabled
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/S

#282 (0013028) Implement support of multiple security domains in aviatrix_aws_tgw_vpn_conn
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
Labels: documentation, size/S

#281 Fix broken gateway doc links
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
Labels: documentation, size/M

#284 (0013097) Add check for cloud_type when incorrectly using ha_subnet for three types if gateway
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/S

#285 (0013097) Update error messages
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/S

#287 Update description of 'vendor_type' in data source firenet vendor integration
  aviatrix/data_source_aviatrix_firenet_vendor_integration.go
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
Labels: documentation, size/XS

#288 (0013097): Add check to include OCI provider for cloud_type when incorrectly using ha_subnet attribute for gateways
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/S

#289 Add check to throw error for 'vpn_protocol' being set as UDP for vpn gateway with elb under non aws providers
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#290 Update error message for gateway resource
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#283 (0013103) Add support of active active ha for site2cloud
  aviatrix/resource_aviatrix_site2cloud.go
  goaviatrix/site2cloud.go
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/M

#286 Add update notes for tgw_vpn_conn
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#291 (0013097) Add check for ha_gw_size which is only needed for enabling ha
  aviatrix/resource_aviatrix_gateway.go
Labels: size/XS

#292 Update R2.11 Docs
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/XS

#293 Release v2.11.0
  CHANGELOG.md
  version
Labels: size/XS

#294 Update R2.11 release notes, compat charts + docs
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#297 (0013210) Add support to handle the case of enabling activemesh and attaching to transit at the same time in update func
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/S

#295 (0013224) Update test-infra to create a private subnet and a routing table for azure vpc for acceptance test
  test-infra/arm/main.tf
  test-infra/arm/vars.tf
  test-infra/aviatrix.tf
  test-infra/variables.tf
Labels: size/S

#298 (0013061) Add a flag for enabling/disabling transit_firenet for transit gateway
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#300 (0013210) Implement a fix to cover all cases of updating active_mesh and transit_gw
  aviatrix/resource_aviatrix_spoke_gateway.go
Labels: size/S

#299 (0013061) Implement add/delete spoke to transit firenet inspection by creating a new resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_transit_firenet_inspection.go
  goaviatrix/transit_firenet.go
Labels: size/L

#301 (0013061) Update 'aviatrix_transit_firenet_inspection.go' to 'aviatrix_transit_firenet_policy.go'
  aviatrix/provider.go
  aviatrix/resource_aviatrix_transit_firenet_policy.go
Labels: size/M

#303 (0013061) Update aviatrix_transit_firenet_policy resource
  aviatrix/resource_aviatrix_transit_firenet_policy.go
  goaviatrix/transit_firenet_policy.go
Labels: size/M

#302 (0013061) Implement enable/disable firewall management access for transit firenet by creating a new resource
  aviatrix/provider.go
  aviatrix/resource_aviatrix_firewall_management_access.go
  goaviatrix/firewall_management_access.go
Labels: size/L

#305 (0013061) Finish transit firenet implement due to backend fix
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/firewall_management_access.go
  goaviatrix/gateway.go
  goaviatrix/transit_firenet_policy.go
Labels: size/L

#306 (13304) Add private_ip, instance_id and security_group_id as computedattribute for all three gateways
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/S

#307 (13061) Implement acceptance test for transit firenet policy
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_transit_firenet_policy_test.go
  test-infra/README_accep_test.md
  website/docs/r/aviatrix_transit_firenet_policy.html.markdown
Labels: documentation, size/XL

#308 (13061) Update logic of enable_transit_firenet to cover arm provider
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
Labels: size/XS
