Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-05, with the labels that each got.

#409 R2.14 documentation updates
  CHANGELOG.md
  docs/FeatureCompatibility.xlsx
  website/docs/d/aviatrix_account.html.markdown
  website/docs/d/aviatrix_caller_identity.html.markdown
  website/docs/d/aviatrix_firenet.html.markdown
  website/docs/d/aviatrix_firenet_vendor_integration.html.markdown
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/d/aviatrix_spoke_gateway.html.markdown
  website/docs/d/aviatrix_transit_gateway.html.markdown
  website/docs/d/aviatrix_vpc.html.markdown
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/r/aviatrix_aws_peer.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_directconnect.html.markdown
  website/docs/r/aviatrix_aws_tgw_peering.html.markdown
  website/docs/r/aviatrix_aws_tgw_peering_domain_conn.html.markdown
  website/docs/r/aviatrix_aws_tgw_transit_gateway_attachment.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_azure_peer.html.markdown
  website/docs/r/aviatrix_azure_spoke_native_peering.html.markdown
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_firewall_tag.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_geo_vpn.html.markdown
  website/docs/r/aviatrix_rbac_group.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_external_device_conn.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
  website/docs/r/aviatrix_vpn_user_accelerator.html.markdown
Labels: documentation, size/XL

#410 Update supported version to latest 5.4-patch/5.4.1201
  CHANGELOG.md
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#411 Update doc dates + release version
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#412 Update go mod to compatible with go 1.14
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#413 (0014613) Fix issue where transit external device conn is forced to recreate caused by connection_type not set correctly
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  goaviatrix/transit_external_device_conn.go
Labels: size/M

#418 Release v2.14.1
  CHANGELOG.md
  version
Labels: size/XS

#419 Update docs for R2.14.1
  docs/FeatureCompatibility.xlsx
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
Labels: documentation, size/XS

#375 (11363) Add support for option to manage attachment on either vpn_profile/vpn_user
  aviatrix/data_source_aviatrix_firewall.go
  aviatrix/resource_aviatrix_vpn_profile.go
  aviatrix/resource_aviatrix_vpn_user.go
  goaviatrix/vpn_user.go
Labels: size/XL

#421 (14717) Refactor to use constants for cloud provider id
  aviatrix/data_source_aviatrix_gateway.go
  aviatrix/data_source_aviatrix_spoke_gateway.go
  aviatrix/data_source_aviatrix_transit_gateway.go
  aviatrix/data_source_aviatrix_vpc_tracker.go
  aviatrix/resource_aviatrix_account.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_geo_vpn.go
  aviatrix/resource_aviatrix_geo_vpn_test.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_spoke_vpc.go
  aviatrix/resource_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_transit_vpc.go
  aviatrix/resource_aviatrix_vpc.go
  goaviatrix/const.go
  goaviatrix/spoke_vpc.go
  goaviatrix/transit_vpc.go
  goaviatrix/vpc.go
  goaviatrix/vpc_tracker.go
Labels: size/XL

#423 (14697) Fix gateway_snat error
  aviatrix/resource_aviatrix_gateway_snat.go
  goaviatrix/gateway.go
Labels: size/S

#422 (13968) Update FQDN tag param
  aviatrix/resource_aviatrix_fqdn.go
  goaviatrix/fqdn.go
  website/docs/r/aviatrix_fqdn.html.markdown
Labels: documentation, size/XS

#424 (0014085): Implement support of adding new users with Geo VPN
  aviatrix/resource_aviatrix_vpn_user.go
  goaviatrix/vpn_user.go
  website/docs/r/aviatrix_vpn_user.html.markdown
Labels: documentation, size/M

#417 (14155) Add ha_peering_subnet option for GCP gateway
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/S
