Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-04, with the labels that each got.

#358 (0013779) Update markdown of aws_tgw to add description of 'manage_transit_gateway_attachment'
  website/docs/r/aviatrix_aws_tgw.html.markdown
Labels: documentation, size/XS

#359 Release v2.13.0
  CHANGELOG.md
  version
Labels: size/XS

#360 Fix test infra due to recent aviatrix module change
  test-infra/aviatrix.tf
Labels: size/XS

#361 Update acceptance test timeout to 10 hours
  GNUmakefile
Labels: size/XS

#362 R2.13 documentation updates
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/index.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_account_user.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_transit_gateway_attachment.html.markdown
  website/docs/r/aviatrix_rbac_group.html.markdown
  website/docs/r/aviatrix_rbac_group_access_account_attachment.html.markdown
  website/docs/r/aviatrix_rbac_group_permission_attachment.html.markdown
  website/docs/r/aviatrix_rbac_group_user_attachment.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/M

#363 Update changelog to correct two resource names for 2.13.0 release
  CHANGELOG.md
Labels: size/XS

#365 Implement logrus to introduce actual log level distinctions
  go.mod
  go.sum
  goaviatrix/README.md
  goaviatrix/account.go
  goaviatrix/account_user.go
  goaviatrix/arm_peering.go
  goaviatrix/aws_peering.go
  goaviatrix/aws_tgw.go
  goaviatrix/aws_tgw_directconnect.go
  goaviatrix/aws_tgw_vpn_conn.go
  goaviatrix/azure_peering.go
  goaviatrix/client.go
  goaviatrix/controller.go
  goaviatrix/firewall.go
  goaviatrix/firewall_tag.go
  goaviatrix/fqdn.go
  goaviatrix/gateway.go
  goaviatrix/geo_vpn.go
  goaviatrix/profile.go
  goaviatrix/rbac_goup_access_account_attachment.go
  goaviatrix/rbac_group.go
  goaviatrix/rbac_group_permission_attachment.go
  goaviatrix/rbac_group_user_attachment.go
  goaviatrix/site2cloud.go
  goaviatrix/spoke_vpc.go
  goaviatrix/tags.go
  goaviatrix/transit_firenet_policy.go
  goaviatrix/transit_gateway_peering.go
  goaviatrix/transit_vpc.go
  goaviatrix/transitive_peering.go
  goaviatrix/tunnel.go
  goaviatrix/version.go
  goaviatrix/vpc.go
Labels: size/L

#366 R2.13 Doc updates pt2
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_rbac_group_permission_attachment.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#367 Run "go mod" for latest implementation of logrus to introduce actual log level distinctions
  CHANGELOG.md
  goaviatrix/transitive_peering.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.golangci.yml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#368 Update controller supported version to latest 5.4-patch version
  CHANGELOG.md
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
Labels: documentation, size/XS

#369 (0013704) Add support for dynamically updating 'customized_route_advertise' in 'aws_tgw_vpc_attachment' resource
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  goaviatrix/aws_tgw_vpc_attachment.go
Labels: size/S

#371 (0012496): Implement a new resource for AWS TGW inter region peering support
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw_peering.go
  goaviatrix/aws_tgw_peering.go
Labels: size/L

#372 (0014074) Implement new resource aviatrix_external_device_conn
  aviatrix/provider.go
  aviatrix/resource_aviatrix_external_device_conn.go
  goaviatrix/external_device_conn.go
Labels: size/XL

#373 Update supported version to include '5.4' in future branch
  aviatrix/provider.go
Labels: size/XS

#374 (0014074) Rename 'aviatrix_external_device_conn' to 'aviatrix_transit_external_device_conn'
  aviatrix/provider.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
Labels: size/XS

#376 (0014074) Update two attribute names to be consistent with resource site2cloud
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  goaviatrix/transit_external_device_conn.go
Labels: size/M

#377 (0014074) Update name of attributes ending with '_number' to ending with '_num' to be consistent with vgw_conn
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_vgw_conn.go
  goaviatrix/transit_external_device_conn.go
Labels: size/L

#379 (0013360) Implement support SAML login for controller inside saml_endpoint
  aviatrix/resource_aviatrix_saml_endpoint.go
  goaviatrix/saml_endpoint.go
Labels: size/M

#380 (0013360) Add 'controller_login' to differentiate if it is a saml for controller login
  aviatrix/resource_aviatrix_saml_endpoint.go
  goaviatrix/saml_endpoint.go
Labels: size/XS

#381 (0013360): Update markdown of 'saml_endpoint' to add description of support for controller login
  website/docs/r/aviatrix_saml_endpoint.html.markdown
Labels: documentation, size/XS

#385 (0012496) Add a markdown for aviatrix_aws_tgw_peering
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_aws_tgw_peering.html.markdown
Labels: documentation, size/S

#386 (0014074) Fix unit test issues found in aviatrix_transit_external_device_conn
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  goaviatrix/transit_external_device_conn.go
Labels: size/M

#384 (0012496) Implement acceptance test for aviatrix_aws_tgw_peering
  aviatrix/resource_aviatrix_aws_tgw_peering_test.go
  goaviatrix/aws_tgw_peering.go
Labels: size/L

#383 (0012496): Implement a new resource for domain connection support between two peered tgws
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw_peering_domain_conn.go
  goaviatrix/aws_tgw_peering_domain_conn.go
Labels: size/L

#387 (0012496): Implement acceptance test for aws_tgw_peering_domain_conn
  aviatrix/resource_aviatrix_aws_tgw_peering_domain_conn_test.go
  goaviatrix/aws_tgw_peering_domain_conn.go
Labels: size/L

#388 (0012496): Create markdown for aws_tgw_peering_domain_conn
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_aws_tgw_peering_domain_conn.html.markdown
Labels: documentation, size/S

#389 (0014074) Implement acceptance test for aviatrix_transit_external_device_conn
  aviatrix/resource_aviatrix_transit_external_device_conn_test.go
Labels: size/M

#390 (0014074) Add a markdown for aviatrix_transit_external_device_conn
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_transit_external_device_conn.html.markdown
Labels: documentation, size/M

#392 (0014138) Implement data source for aviatrix_vpc
  aviatrix/data_source_aviatrix_vpc.go
  aviatrix/provider.go
Labels: size/L

#393 (0013570) Fix issue where it is not able to modify OpenVPN that is Attached to GeoVPN
  aviatrix/resource_aviatrix_gateway.go
  goaviatrix/gateway.go
  goaviatrix/geo_vpn.go
  goaviatrix/split_tunnel.go
Labels: size/M

#394 Merge commits for 2.14.0 release from future to master
  aviatrix/data_source_aviatrix_vpc.go
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw_peering_domain_conn.go
  aviatrix/resource_aviatrix_aws_tgw_peering_domain_conn_test.go
  aviatrix/resource_aviatrix_aws_tgw_peering_test.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_saml_endpoint.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_transit_external_device_conn_test.go
  aviatrix/resource_aviatrix_vgw_conn.go
  goaviatrix/aws_tgw_peering.go
  goaviatrix/aws_tgw_peering_domain_conn.go
  goaviatrix/gateway.go
  goaviatrix/geo_vpn.go
  goaviatrix/saml_endpoint.go
  goaviatrix/split_tunnel.go
  goaviatrix/transit_external_device_conn.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_aws_tgw_peering.html.markdown
  website/docs/r/aviatrix_aws_tgw_peering_domain_conn.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_transit_external_device_conn.html.markdown
Labels: documentation, size/XXL

#395 (0014138) Implement acceptance test for data source vpc
  aviatrix/data_source_aviatrix_vpc_test.go
  aviatrix/resource_aviatrix_transit_external_device_conn_test.go
Labels: size/M

#396 (0014138) Add markdown for data source vpc
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/d/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#397 (0014157) Add hagw name as computed vale for gateway, spoke gateway and transit gateway
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#398 (0014137) Update data source transit gateway to be latest
  aviatrix/data_source_aviatrix_transit_gateway.go
  website/docs/d/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/L

#399 (0014137) Update data source spoke gateway to be latest
  aviatrix/data_source_aviatrix_spoke_gateway.go
  website/docs/d/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/L

#400 (0014137) Update data source gateway to be latest
  aviatrix/data_source_aviatrix_gateway.go
  website/docs/d/aviatrix_gateway.html.markdown
Labels: documentation, size/XL

#401 (0014137) Update attribute description in all three kinds of gateway data source
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/d/aviatrix_spoke_gateway.html.markdown
  website/docs/d/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#402 (0014137) Add 'peering_ha_public_ip' and 'peering_ha_private_ip' as computed value for aviatrix_gateway
  aviatrix/data_source_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway.go
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/M

#404 (0014137) Add 'ha_private_ip' as computed value for aviatrix_transit_gateway
  aviatrix/data_source_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/d/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#405 (0014137) Remove computed value of 'public_ip' to avoid redundancy for aviatrixt_gateway
  aviatrix/data_source_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway.go
  website/docs/d/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
Labels: documentation, size/XS

#407 Update test-infra to cover newly added data source and reources
  test-infra/cmdExportOutput.sh
Labels: size/XS

#406 Release v2.14.0
  CHANGELOG.md
  version
Labels: size/XS

#408 Fix acceptance test for data source of three gateways
  aviatrix/data_source_aviatrix_gateway_test.go
  aviatrix/data_source_aviatrix_spoke_gateway_test.go
  aviatrix/data_source_aviatrix_transit_gateway_test.go
Labels: size/S
