Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-06, with the labels that each got.

#425 (14155) Add ha_subnet option to GCP transit gw
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#426 (0014695) Update 'tunnel_type' option to be 'policy' and 'route' to line up with Controller6.0
  aviatrix/resource_aviatrix_site2cloud.go
  goaviatrix/site2cloud.go
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/XS

#427 Revert "(14697) Fix gateway_snat error"
  aviatrix/resource_aviatrix_gateway_snat.go
  goaviatrix/gateway.go
Labels: size/S

#428 (14155) Add ha_subnet to spoke gw GCP
  aviatrix/resource_aviatrix_spoke_gateway.go
  goaviatrix/spoke_vpc.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/M

#429 (14138) Add route_tables and route_tables_filter to data_source_vpc
  aviatrix/data_source_aviatrix_vpc.go
  goaviatrix/vpc.go
  website/docs/d/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#430 (0014965) Implement support of IKE version in Terraform
  aviatrix/resource_aviatrix_site2cloud.go
  goaviatrix/site2cloud.go
  website/docs/r/aviatrix_site2cloud.html.markdown
Labels: documentation, size/XS

#431 Update validation function to use default function
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway_snat.go
  aviatrix/resource_aviatrix_rbac_group_permission_attachment.go
  aviatrix/resource_aviatrix_saml_endpoint.go
  aviatrix/resource_aviatrix_site2cloud.go
Labels: size/M

#432 (0015201) Fix ha gateway creation issue in spoke_gateway and transit_gateway
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/M

#434 (0015316) Update aviatrix_vpc to return parsed vpc_id for GCP provider
  aviatrix/resource_aviatrix_vpc.go
Labels: size/XS

#436 (0015317) Fix issue where Azure Transit HA creation fails with insane mode enabled
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#435 (13388) Branch router tag
  aviatrix/data_source_aviatrix_vpc.go
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router.go
  aviatrix/resource_aviatrix_branch_router_tag.go
  aviatrix/resource_aviatrix_branch_router_tag_test.go
  aviatrix/resource_aviatrix_branch_router_test.go
  goaviatrix/branch_router.go
  goaviatrix/branch_router_tag.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_branch_router_tag.html.markdown
Labels: documentation, size/XL

#438 (14155) Fix ha subnet import for gcp gateways
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#439 Fix acceptance test for site2cloud
  aviatrix/resource_aviatrix_site2cloud.go
  aviatrix/resource_aviatrix_site2cloud_test.go
  goaviatrix/site2cloud.go
Labels: size/XS

#440 (0015429) Fix issue where custom_saml_request_template output is null after creation in aviatrix_saml_endpoint
  aviatrix/resource_aviatrix_saml_endpoint.go
  goaviatrix/saml_endpoint.go
Labels: size/XS

#441 Add acceptance test for data source firewall and vpc_tracker
  test-infra/cmdExportOutput.sh
Labels: size/XS

#442 (14155) Fix gateway ha_subnet deletion issue
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XS

#443 (15427) Fix GCP account creation
  aviatrix/resource_aviatrix_account.go
  goaviatrix/account.go
  goaviatrix/client.go
Labels: size/L

#444 (0015467) Fix issue where an error is returned for enabling encrypted volume for gateway with ha on first apply
  goaviatrix/gateway.go
Labels: size/XS

#445 Add setting 'enable_active_mesh' into examples for spoke gateway and transit gateway
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#446 (15461) Fix vpc tracker unmarshal error
  goaviatrix/vpc_tracker.go
Labels: size/XS

#447 (0015467) Update terraform to cover the case that encrypt volume is enabled with gateway creation on 6.0
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  goaviatrix/spoke_vpc.go
  goaviatrix/transit_vpc.go
Labels: size/S

#452 Update supported version to 6.0
  aviatrix/provider.go
Labels: size/XS

#448 (13388) Branch router interface and IP
  aviatrix/resource_aviatrix_account.go
  aviatrix/resource_aviatrix_branch_router.go
  aviatrix/resource_aviatrix_branch_router_tag.go
  aviatrix/resource_aviatrix_branch_router_tag_test.go
  aviatrix/resource_aviatrix_branch_router_test.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_saml_endpoint.go
  aviatrix/resource_aviatrix_site2cloud.go
  aviatrix/resource_aviatrix_site2cloud_test.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_vpn_user_test.go
  goaviatrix/account.go
  goaviatrix/branch_router.go
  goaviatrix/gateway.go
  goaviatrix/saml_endpoint.go
  goaviatrix/site2cloud.go
  goaviatrix/spoke_vpc.go
  goaviatrix/transit_vpc.go
  goaviatrix/vpc_tracker.go
  test-infra/cmdExportOutput.sh
  website/docs/r/aviatrix_branch_router.html.markdown
  website/docs/r/aviatrix_branch_router_tag.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/XL

#455 Rebase CloudWAN branch to be up to date with master
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router.go
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#453 Release v2.15.0
  CHANGELOG.md
  version
Labels: size/XS

#456 Fix merge leftover in docs
  website/docs/r/aviatrix_spoke_gateway.html.markdown
Labels: documentation, size/XS

#458 (0015678) Fix issue where Terraform destroy failed on SpokeGW configured with prior customized SNAT configs
  aviatrix/resource_aviatrix_gateway_snat.go
  goaviatrix/gateway.go
Labels: size/XS

#460 (15678) Change 'interface' under snat_policy to be default 'etho'
  aviatrix/resource_aviatrix_gateway_snat.go
Labels: size/XS

#461 (15678) Update description for 'interface' under snat_policy
  aviatrix/resource_aviatrix_gateway_snat.go
  website/docs/r/aviatrix_gateway_snat.html.markdown
Labels: documentation, size/XS

#462 Doc updates for (15678) custom SNAT fix
  CHANGELOG.md
  website/docs/guides/feature-changelist-v2.html.markdown
Labels: documentation, size/XS

#463 (0015715): Fix issue where disabling SNAT fails due to changed API usage for gateway.go
  aviatrix/resource_aviatrix_gateway_snat.go
  goaviatrix/gateway.go
Labels: size/XS

#464 Update changelog to add tested controller version
  CHANGELOG.md
Labels: size/XS

#459 (14894) Add excluded network CIDRs and tgw connections to tgw peering
  aviatrix/resource_aviatrix_transit_gateway_peering.go
  goaviatrix/transit_gateway_peering.go
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
Labels: documentation, size/L

#465 (13388) Branch router transit gateway attachment
  aviatrix/provider.go
  aviatrix/resource_aviatrix_branch_router_avx_tgw_attachment.go
  aviatrix/resource_aviatrix_branch_router_avx_tgw_attachment_test.go
  goaviatrix/branch_router.go
  goaviatrix/branch_router_avx_tgw_attachment.go
  goaviatrix/site2cloud.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_branch_router_avx_tgw_attachment.html.markdown
Labels: documentation, size/XL

#467 (0015610) Remove condition that single_az_ha has to be disabled to enable encrypt volume
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
Labels: size/XS

#469 0015841: Update ASN to support 4-Byte ASN
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  aviatrix/resource_aviatrix_transit_external_device_conn.go
  aviatrix/resource_aviatrix_vgw_conn.go
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_transit_external_device_conn.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
Labels: documentation, size/M
