Repository AviatrixSystems/terraform-provider-aviatrix, pull requests merged in 2020-03, with the labels that each got.

#311 (13392) Implement support for arm provider in aviatrix_vpc
  aviatrix/resource_aviatrix_vpc.go
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/XS

#312 (13427) Fix the issue where firewall_instance will force replacement if firewall_image_version is not set
  aviatrix/resource_aviatrix_firewall_instance.go
Labels: size/XS

#313 (13404) Add 'ha_cloud_instance_id' as a computed attribute in spoke and transit gateway resources
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_transit_gateway.go
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/S

#314 (13392) Implement acceptance test for arm provider in vpc resource
  aviatrix/resource_aviatrix_vpc_test.go
Labels: size/L

#315 (13096) Implement attaching arm spoke through native peering
  aviatrix/provider.go
  aviatrix/resource_aviatrix_azure_spoke_native_peering.go
  goaviatrix/azure_spoke_native_peering.go
Labels: size/L

#317 (13096) Create markdown for aviatrix_azure_spoke_native_peering
  aviatrix/resource_aviatrix_azure_spoke_native_peering.go
  website/aviatrix.erb
  website/docs/r/aviatrix_azure_spoke_native_peering.html.markdown
Labels: documentation, size/S

#304 Add note regarding enable_firenet for transit_gateway
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/S

#318 (13474) Add a new resource aviatrix_zure_peer
  aviatrix/provider.go
  aviatrix/resource_aviatrix_azure_peer.go
  aviatrix/resource_aviatrix_azure_peer_test.go
  goaviatrix/azure_peering.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_azure_peer.html.markdown
Labels: documentation, size/XL

#319 (0013474): Add note to arm_peer markdown to deprecate arm_peer resource
  website/docs/r/aviatrix_arm_peer.html.markdown
Labels: documentation, size/XS

#320 (13096) Implement acceptance test for aviatrix_azure_spoke_native_peering
  aviatrix/resource_aviatrix_azure_spoke_native_peering_test.go
  test-infra/README_accep_test.md
Labels: size/L

#322 Update 'arm' to 'azre' in all acceptance test, messages in all resources and data sources
  aviatrix/data_source_aviatrix_spoke_gateway_test.go
  aviatrix/data_source_aviatrix_transit_gateway_test.go
  aviatrix/resource_aviatrix_account.go
  aviatrix/resource_aviatrix_account_test.go
  aviatrix/resource_aviatrix_azure_spoke_native_peering.go
  aviatrix/resource_aviatrix_firewall_management_access_test.go
  aviatrix/resource_aviatrix_gateway.go
  aviatrix/resource_aviatrix_gateway_dnat_test.go
  aviatrix/resource_aviatrix_gateway_snat_test.go
  aviatrix/resource_aviatrix_gateway_test.go
  aviatrix/resource_aviatrix_spoke_gateway.go
  aviatrix/resource_aviatrix_spoke_gateway_test.go
  aviatrix/resource_aviatrix_spoke_vpc.go
  aviatrix/resource_aviatrix_spoke_vpc_test.go
  aviatrix/resource_aviatrix_transit_firenet_policy_test.go
  aviatrix/resource_aviatrix_transit_gateway.go
  aviatrix/resource_aviatrix_transit_gateway_test.go
  aviatrix/resource_aviatrix_transit_vpc_test.go
  aviatrix/resource_aviatrix_vpc.go
  aviatrix/resource_aviatrix_vpc_test.go
  test-infra/README_accep_test.md
  test-infra/aviatrix.tf
  test-infra/azure/main.tf
  test-infra/azure/outputs.tf
  test-infra/azure/vars.tf
  test-infra/cmdExportOutput.sh
Labels: size/XL

#323 Update test_infra to cover added new resources
  test-infra/outputs.tf
  test-infra/provider.tf
Labels: size/XS

#324 R2.12 doc updates PR#1
  website/aviatrix.erb
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/v2-upgrade-guide.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_account_user.html.markdown
  website/docs/r/aviatrix_arm_peer.html.markdown
  website/docs/r/aviatrix_aws_peer.html.markdown
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_directconnect.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
  website/docs/r/aviatrix_azure_peer.html.markdown
  website/docs/r/aviatrix_azure_spoke_native_peering.html.markdown
  website/docs/r/aviatrix_controller_config.html.markdown
  website/docs/r/aviatrix_firenet.html.markdown
  website/docs/r/aviatrix_firewall.html.markdown
  website/docs/r/aviatrix_firewall_instance.html.markdown
  website/docs/r/aviatrix_firewall_management_access.html.markdown
  website/docs/r/aviatrix_firewall_tag.html.markdown
  website/docs/r/aviatrix_fqdn.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_gateway_dnat.html.markdown
  website/docs/r/aviatrix_gateway_snat.html.markdown
  website/docs/r/aviatrix_spoke_vpc.html.markdown
  website/docs/r/aviatrix_transit_firenet_policy.html.markdown
  website/docs/r/aviatrix_transit_vpc.html.markdown
Labels: documentation, size/XL

#325 (13505) Fix the issue where dnat resource creation fails
  aviatrix/resource_aviatrix_gateway_dnat.go
  goaviatrix/gateway.go
Labels: size/XS

#316 (13438) Implement support of username and password in firewall_instance resource for azure provider
  aviatrix/resource_aviatrix_firewall_instance.go
  goaviatrix/firewall_instance.go
  website/docs/r/aviatrix_firewall_instance.html.markdown
Labels: documentation, size/S

#326 Update 'arm' to 'azure' in all markdowns
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_gateway_dnat.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
Labels: documentation, size/M

#327 Release v2.12.0
  CHANGELOG.md
  version
Labels: size/S

#328 (13366) Clear up wording on TGW VPC attachment documentation regarding 'customized_route_advertisement' and 'disable_local_route_propagation'
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_vpc_attachment.go
  website/docs/r/aviatrix_aws_tgw.html.markdown
  website/docs/r/aviatrix_aws_tgw_vpc_attachment.html.markdown
Labels: documentation, size/XS

#329 (0013563) Set egress to disabled when destroying the firenet resource
  aviatrix/resource_aviatrix_firenet.go
Labels: size/XS

#330 R2.12 doc updates PR#2
  docs/FeatureCompatibility.xlsx
  website/docs/guides/feature-changelist-v2.html.markdown
  website/docs/guides/release-compatibility.html.markdown
  website/docs/guides/release-notes.html.markdown
  website/docs/r/aviatrix_account.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_geo_vpn.html.markdown
  website/docs/r/aviatrix_saml_endpoint.html.markdown
  website/docs/r/aviatrix_site2cloud.html.markdown
  website/docs/r/aviatrix_spoke_gateway.html.markdown
  website/docs/r/aviatrix_trans_peer.html.markdown
  website/docs/r/aviatrix_transit_firenet_policy.html.markdown
  website/docs/r/aviatrix_transit_gateway.html.markdown
  website/docs/r/aviatrix_transit_gateway_peering.html.markdown
  website/docs/r/aviatrix_tunnel.html.markdown
  website/docs/r/aviatrix_vgw_conn.html.markdown
  website/docs/r/aviatrix_vpc.html.markdown
  website/docs/r/aviatrix_vpn_profile.html.markdown
  website/docs/r/aviatrix_vpn_user.html.markdown
  website/docs/r/aviatrix_vpn_user_accelerator.html.markdown
Labels: documentation, size/L

#331 Enhance test-infra to cover acceptance test of newly added resources
  CHANGELOG.md
  test-infra/cmdExportOutput.sh
  test-infra/outputs.tf
Labels: size/XS

#332 Update test-infra to fix acceptance test for new resources
  aviatrix/resource_aviatrix_transit_firenet_policy_test.go
  test-infra/cmdExportOutput.sh
  test-infra/variables.tf
Labels: size/XS

#333 Update markdown of data source firenet
  website/docs/d/aviatrix_firenet.html.markdown
Labels: documentation, size/XS

#335 Update aviatrix provider index markdown
  website/docs/index.html.markdown
Labels: documentation, size/XS

#338 (0013644) Fix the issue where changes in vpc_name results in subnets being mismatched in terraform causing issues
  aviatrix/resource_aviatrix_aws_tgw.go
Labels: size/XS

#340 (13737) Remove 'account_name' from account_user resource for RBAC implementation for 5.4
  aviatrix/resource_aviatrix_account_user.go
  website/docs/r/aviatrix_account_user.html.markdown
Labels: documentation, size/S

#341 (0013737) Implement new resource rbac_group for rbac implementation
  aviatrix/provider.go
  aviatrix/resource_aviatrix_rbac_group.go
  goaviatrix/rbac_group.go
Labels: size/L

#342 (0013737) Implement new resource rbac_group_user_attachment for rbac implementation
  aviatrix/provider.go
  aviatrix/resource_aviatrix_rbac_group.go
  aviatrix/resource_aviatrix_rbac_group_user_attachment.go
  goaviatrix/rbac_group_user_attachment.go
Labels: size/L

#343 (0013737) Implement new resource rbac_group_account_attachment for rbac implementation
  aviatrix/provider.go
  aviatrix/resource_aviatrix_rbac_group_access_account_attachment.go
  goaviatrix/rbac_goup_access_account_attachment.go
Labels: size/XL

#344 (0013737) Implement new resource rbac_group_permission_attachment for rbac implementation
  aviatrix/provider.go
  aviatrix/resource_aviatrix_rbac_group_permission_attachment.go
  goaviatrix/rbac_group_permission_attachment.go
Labels: size/L

#345 (0013647) Add support for learned_cidrs_approval for transit gateway
  aviatrix/resource_aviatrix_transit_gateway.go
  goaviatrix/gateway.go
  goaviatrix/transit_vpc.go
  website/docs/r/aviatrix_transit_gateway.html.markdown
Labels: documentation, size/M

#346 (0013647) Add support for learned_cidrs_approval for aws_tgw_vpn_conn
  aviatrix/resource_aviatrix_aws_tgw_vpn_conn.go
  goaviatrix/aws_tgw_vpn_conn.go
  website/docs/r/aviatrix_aws_tgw_vpn_conn.html.markdown
Labels: documentation, size/L

#347 (0013647) Add support for learned_cidrs_approval for aws_tgw_directconnect
  aviatrix/resource_aviatrix_aws_tgw_directconnect.go
  goaviatrix/aws_tgw_directconnect.go
  website/docs/r/aviatrix_aws_tgw_directconnect.html.markdown
Labels: documentation, size/M

#348 (0013779) Enhance read back of 'attached_aviatrix_transit_gateway' to cover multiple transit gateways created on the same vpc
  goaviatrix/aws_tgw.go
Labels: size/S

#349 (0013779) Implement a new resource 'aviatrix_aws_tgw_transit_gateway_attachment' to decouple transit gw attachment from aviatrix_aws_tgw
  aviatrix/provider.go
  aviatrix/resource_aviatrix_aws_tgw.go
  aviatrix/resource_aviatrix_aws_tgw_transit_gateway_attachment.go
  goaviatrix/aws_tgw.go
  goaviatrix/aws_tgw_transit_gateway_attachment.go
Labels: size/XL

#350 (0013737) Implement acceptance test for new resource rbac_group
  aviatrix/resource_aviatrix_rbac_group_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_rbac_group.html.markdown
Labels: documentation, size/M

#351 (0013737) Implement acceptance test for new resource rbac_group_access_account_attachment
  aviatrix/resource_aviatrix_rbac_group_access_account_attachment_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_rbac_group_access_account_attachment.html.markdown
Labels: documentation, size/L

#352 (0013737) Implement acceptance test for new resource rbac_group_user_attachment
  aviatrix/resource_aviatrix_rbac_group_user_attachment_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_rbac_group_user_attachment.html.markdown
Labels: documentation, size/L

#354 Merge 'rbac' feature to master for 5.4 release
  aviatrix/provider.go
  aviatrix/resource_aviatrix_account_user.go
  aviatrix/resource_aviatrix_rbac_group.go
  aviatrix/resource_aviatrix_rbac_group_access_account_attachment.go
  aviatrix/resource_aviatrix_rbac_group_access_account_attachment_test.go
  aviatrix/resource_aviatrix_rbac_group_permission_attachment.go
  aviatrix/resource_aviatrix_rbac_group_permission_attachment_test.go
  aviatrix/resource_aviatrix_rbac_group_test.go
  aviatrix/resource_aviatrix_rbac_group_user_attachment.go
  aviatrix/resource_aviatrix_rbac_group_user_attachment_test.go
  goaviatrix/rbac_goup_access_account_attachment.go
  goaviatrix/rbac_group.go
  goaviatrix/rbac_group_permission_attachment.go
  goaviatrix/rbac_group_user_attachment.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_account_user.html.markdown
  website/docs/r/aviatrix_gateway.html.markdown
  website/docs/r/aviatrix_rbac_group.html.markdown
  website/docs/r/aviatrix_rbac_group_access_account_attachment.html.markdown
  website/docs/r/aviatrix_rbac_group_permission_attachment.html.markdown
  website/docs/r/aviatrix_rbac_group_user_attachment.html.markdown
Labels: documentation, size/XXL

#355 (0013779) Implement acceptance test for new resource 'aviatrix_aws_tgw_transit_gateway_attachment'
  aviatrix/resource_aviatrix_aws_tgw_transit_gateway_attachment_test.go
  aviatrix/resource_aviatrix_rbac_group_permission_attachment_test.go
  test-infra/README_accep_test.md
  website/aviatrix.erb
  website/docs/r/aviatrix_aws_tgw_transit_gateway_attachment.html.markdown
Labels: documentation, size/L

#357 Fix acceptance test for account_user
  aviatrix/resource_aviatrix_account_user_test.go
Labels: size/XS
